version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: property_market_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - estate_market_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: stefanpopescu923@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - estate_market_network
    restart: unless-stopped
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    links:
      - alertmanager:alertmanager
    networks:
      - estate_market_network
    restart: always

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    networks:
      - estate_market_network
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager/:/etc/alertmanager/
    networks:
      - estate_market_network
    restart: always
    command:
      - "--config.file=/etc/alertmanager/alertmanager-config.yml"
      - "--storage.path=/alertmanager"

  backend:
    build: ../src/
    image: backend-image:latest
    container_name: backend
    environment:
      - PORT=5000
    ports:
      - "8080:5000"
    networks:
      - estate_market_network
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ../src/
    image: frontend-image:latest
    container_name: frontend
    environment:
      - PORT=80
    ports:
      - "80:4200"
    networks:
      - estate_market_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  prometheus_data:

networks:
  estate_market_network:
    driver: bridge