database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "admin"
  databaseName: "property_market_db"
  sslMode: "disable"
  maxIdleConnections: 15
  maxOpenConnections: 100
  connMaxLifetime: 5
auth:
  password:
    bCryptCost: 10
    includeChars: true
    includeDigits: true
    includeUppercase: true
    includeLowercase: true
    minLength: 6
    maxLength: 64
  jwt:
    accessTokenSecret: "accessSecret"
    refreshTokenSecret: "refreshSecret"
    accessTokenExpireDurationMinutes: 1440
    refreshTokenExpireDurationMinutes: 60
server:
  internalPort: 5000
  externalPort: 5000
  runningMode: debug